export { default as Announcement } from "./Announcement/Announcement"; 
export { default as Categories } from "./Categories/Categories"; 
export { default as CategoryItem } from "./CategoryItem/CategoryItem"; 
export { default as Footer } from "./Footer/Footer"; 
export { default as Navbar } from "./Navbar/Navbar"; 
export { default as Newsletter } from "./Newsletter/Newsletter"; 
export { default as Product } from "./Product/Product"; 
export { default as Products } from "./Products/Products"; 
export { default as Slider } from "./Slider/Slider"; 